---

- include: rabbitmq-certificates.yml
  when: mig_rabbitmq_ssl is defined and mig_rabbitmq_ssl

- include: rabbitmq-configure.yml

- name: ensure rabbitmq-server is started and enabled
  service: name=rabbitmq-server enabled=yes state=started
